#!/bin/bash

SYSTEM_FOLDER=/usr/local
DEAMON_FILE=$SYSTEM_FOLDER/bin/deadmans_daemon.sh
ALARM_FILE=$SYSTEM_FOLDER/share/deadman/alarm.ogg

CACHE_FOLDER=~/.cache/deadman
mkdir -p $CACHE_FOLDER
ID_FILE=$CACHE_FOLDER/id.txt

CONFIG_FOLDER=~/.config/deadman
mkdir -p $CONFIG_FOLDER
CONFIG=$CONFIG_FOLDER/minutes_to_death.txt

PID=`cat $ID_FILE 2>/dev/null`

if [[ $PID == "" ]]
then
    STATE=" not"
    ACTION="start"
else
    ACTION="stop"
fi

zenity --question --cancel-label="Cancel" --ok-label="Ok" --title="deadman" --width=300 --icon-name=face-devilish \
    --text="The deadman's daemon is currently$STATE running.\nDo you want to $ACTION it?"

if [[ $? == 0 ]]
then
    if [[ $PID == "" ]]
    then
        $DEAMON_FILE --alarm-file=$ALARM_FILE > /dev/null &
        echo $! > $ID_FILE
    else
        kill $PID
        rm $ID_FILE
    fi
fi
