#!/bin/bash

SYSTEM_FOLDER=/usr/local
DEAMON_FILE=$SYSTEM_FOLDER/bin/deadmans_daemon.sh
ALARM_FILE=$SYSTEM_FOLDER/share/deadman/alarm.ogg

CACHE_FOLDER=~/.cache/deadman
mkdir -p $CACHE_FOLDER
ID_FILE=$CACHE_FOLDER/id.txt

CONFIG_FOLDER=~/.config/deadman
mkdir -p $CONFIG_FOLDER
COUNTDOWN_FILE=$CONFIG_FOLDER/final_countdown.txt
TIMER_FILE=$CONFIG_FOLDER/deadline.txt

PID=$(cat $ID_FILE 2>/dev/null)
test -s $COUNTDOWN_FILE && COUNTDOWN="-c $(cat $COUNTDOWN_FILE 2>/dev/null)"
test -s $TIMER_FILE && TIMER="-t $(cat $TIMER_FILE 2>/dev/null)"

if [[ $PID ]]; then
    ACTION="stop"
else
    STATE=" not"
    ACTION="start"
fi

zenity --question --cancel-label="Cancel" --ok-label="Ok" --title="deadman" --width=300 --icon-name=face-devilish \
    --text="The deadman's daemon is currently$STATE running.\nDo you want to make him $ACTION?"

if ! (($?)); then
    if [[ $PID ]]; then
        kill $PID
        rm -f $ID_FILE
    else
        $DEAMON_FILE --alarm-file=$ALARM_FILE $COUNTDOWN $TIMER >/dev/null &
        echo $! > $ID_FILE
    fi
fi
